export * from './Hero/Hero'
export * from './About/About'
export * from './Button/Button'
export * from './NumberedHeading/NumberedHeading'
export * from './Featured/Featured'
export * from './Projects/Projects'
export * from './Contact/Contact'
export * from './Loader/Loader'
export * from './Email/Email'
export * from './Social/Social'
export * from './Footer/Footer'
export * from './Navbar/Navbar'

